apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: hello-operator2.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: Traveller is the Schema for the travellers API
      displayName: Traveller
      kind: Traveller
      name: travellers.my.domain
      version: v1alpha1
  description: Simple test with operator
  displayName: test
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - test opreator personal-project
  links:
  - name: Hello Operator2
    url: https://hello-operator2.domain
  maintainers:
  - email: erwan.bernard079@gmail.com
    name: erwan
  maturity: alpha
  provider:
    name: simple test
  version: 0.0.0
